### ISSUE TITLE
What to do with containers?

### ISSUE THREAD

**Issue by byrnedo** [gvidon/reacto#3]
Hi, I'm new to react and found this via the https://medium.com/ottofellercom/how-to-structure-large-react-apps-440b0e012d80 blog post. Nice post and this repo has helped get a bit of understanding on how to get structuring a larger react project.

One question though. What's your opinion on containers? 
Maybe I don't need to use containers at all an amn't aware of that?

**Comment by gvidon** [comment]
Hi @byrnedo. Perhaps this comment https://medium.com/@gvidon/andres-londono-i-agree-having-pure-component-can-be-useful-for-tests-and-it-is-23f6f2fe3ab8 should reply to your question.

Shortly — I wouldn't introduce component/container separation as it creates more question than answers when it comes to deep architecture design. But instead I would always have pure version of any component. Which is quite helpful in testing, and is more scalable.

**Comment by byrnedo** [comment]
Thanks!
